### ISSUE TITLE
Adding a2zapk.io as a source

### ISSUE THREAD

**Issue by CaptainKnox** [anfreire/updateMe-Scrapping#6]
This site has native, direct download links and has the latest versions.

**Comment by anfreire** [comment]
Thank you for the suggestion, but unfortunately I won't be able to add a2zapk.io as a source :disappointed: 

The website employs JavaScript that detects the use of developer tools and automated web browsers. When attempting to access the download links, it redirects back to the home page, making it impossible to scrape effectively.

I appreciate your input, but I need sources that allow for reliable automated access to maintain up-to-date mod versions
