### ISSUE TITLE
Suggestion : a repo on github 

### ISSUE THREAD

**Issue by TomBonnot** [anfreire/updateMe-Scrapping#7]
Hello there 
Amazing work with your app. I saw a closed issue talking about revanced extended and revance.net, which I am agreeing because it is not the official repo. 
Tho, there is already repos that automatically rebuilds the apps within minutes after a new update of Revanced Patches : https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root?tab=readme-ov-file 

Maybe it could be a good try ? 
I know you are working on a futur update with your own builds but... yeah, I just wanted to share, you can delete or close if it bother you ! 
Thankyou !

**Comment by anfreire** [comment]
I've now updated all apps that were using revanced.net to use the recommended GitHub repo. I've also added some additional apps from there.

I'm closing this issue as it has been addressed. 

Your input was very helpful! :muscle:

**Comment by TomBonnot** [comment]
Que fixe ! Muito obrigado ! 
Keep up the good work
