### ISSUE TITLE
xManager for Spotify 

### ISSUE THREAD

**Issue by TomBonnot** [anfreire/updateMe-Scrapping#9]
As the title says, you could check to add xManager’s mods for Spotify. https://github.com/Team-xManager/xManager/tree/main?tab=readme-ov-file 
It’s a well known mods creator for spotify

**Comment by anfreire** [comment]
I'm very familiar with xManager and truly admire the project and its creator. It's an excellent tool that I personally love

However, I don't think it will be a good fit for our app at this time. The main reason is that xManager itself notifies users about updates to both the modded Spotify app and xManager itself. There is no need to include the app in the Update Me repository when the app updates itself independently.

I appreciate you thinking of ways to improve our app and taking the time to make this suggestion. Please feel free to share any other ideas you might have 💪

**Comment by TomBonnot** [comment]
I wasn't thinning about integrating xManager into this app, but trying to scrap apk from xManager and put it through Spotify's mods.

I tried to find a way to scrap apks but I couldn't get it right. Thanks for replying !

**Comment by anfreire** [comment]
@TomBonnot  Thanks for clarifying - I see I misunderstood your original suggestion. My apologies for that.

You're right that scraping APKs from xManager could be a valuable approach. I actually tried integrating xManager early on but ran into some challenges. However, given how high-priority this idea is, I think it's worth reopening this issue and giving it another shot.

I'll look into analyzing the requests and see if we can develop a scraping tool to fetch the APKs. It's a tricky task, but potentially very useful if we can get it working.

I'm reopening this issue so we can continue exploring this avenue. If you have any other thoughts or ideas on how to approach this, please feel free to share!

**Comment by TomBonnot** [comment]
I’ve tried through their on repository but it is only accessible with an account, Telegram/Discord. 
It’s a weird way from them to post their apks.

**Comment by anfreire** [comment]
Great news! I'm closing this issue as I've successfully created a script to fetch download links from xManager.

It's now incorporated into our app :trophy: 

Thanks @TomBonnot  for the suggestion

**Comment by TomBonnot** [comment]
I have to admit I am impressed ! Thank you and you’re welcome for the suggestion !
